name: BetterParkour
version: '${project.version}'
main: net.natroutter.betterparkour.BetterParkour
api-version: 1.17
authors: [NATroutter]
description: Simple parkour plugin
website: https://NATroutter.net
softdepend: [HolographicDisplays]