main: fi.natroutter.betterparkour.BetterParkour
name: BetterParkour
version: '${project.version}'
api-version: 1.18
authors: [NATroutter]
description: Simple parkour plugin
website: https://NATroutter.net
depend: [NATLibs]
softdepend: [HolographicDisplays]